---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Talleres FIFA BsAs"
keywords:    "Talleres, LaTeX, Python, FIFA, BsAs, Física"
description: "Talleres impartidos por la FIFA Regional BsAs"
source_link: "https://github.com/fifabsas/talleresfifabsas"
favicon:     "img/favicon.png"
touch_icon:  "img/touch-icon.png"
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:            '#28262c'
  white:            '#f8f8f8'
  blue:             '#49a7e9'
  blue_home:        '#EBF2FA'
  blue_python:      '#410DAB'
  blue_latex:       '#107e7d'
  blue_inscripcion: '#28262c'
  blue_mas_info:    '#A63446'
  green:            '#9bcf2f'
  purple:           '#c869bf'
  orange:           '#fab125'
  turquoise:        '#0fbfcf'

kramdown:
  auto_ids:  false

